/**
 * FeedbackHistory Component
 *
 * Displays user's received feedback with ratings and comments
 * Shows feedback from games, trades, and user interactions
 *
 * Pattern based on: TrendingPostsPanel.tsx
 */

'use client'

import { useEffect, useState } from 'react'
import { MessageSquare, Star, TrendingUp, TrendingDown, AlertCircle } from 'lucide-react'
import { formatDistanceToNow } from 'date-fns'
import { getProfileUrl } from '@/lib/profile-utils'
import Link from 'next/link'

interface FeedbackItem {
  id: string
  fromUserId: string | null
  fromUserName?: string
  fromUsername?: string | null
  score: number // 0-100
  category: string | null
  interactionType: string
  comment: string | null
  createdAt: string
  isAutoGenerated: boolean
  metadata?: {
    gameId?: string
    tradeId?: string
    positionId?: string
  }
}

interface FeedbackHistoryProps {
  userId: string
  limit?: number
  showAutoFeedback?: boolean
  className?: string
}

export function FeedbackHistory({
  userId,
  limit = 10,
  showAutoFeedback = true,
  className = ''
}: FeedbackHistoryProps) {
  const [feedbackItems, setFeedbackItems] = useState<FeedbackItem[]>([])
  const [loading, setLoading] = useState(true)
  const [averageScore, setAverageScore] = useState<number>(0)

  useEffect(() => {
    const fetchFeedbackHistory = async () => {
      setLoading(true)
      const params = new URLSearchParams({
        limit: limit.toString(),
        includeAuto: showAutoFeedback.toString(),
      })
      const response = await fetch(
        `/api/feedback/received/${encodeURIComponent(userId)}?${params}`
      )
      const data = await response.json()

      if (data.success) {
        setFeedbackItems(data.feedback || [])
        setAverageScore(data.averageScore || 0)
      }
      setLoading(false)
    }

    fetchFeedbackHistory()
    // Refresh every 60 seconds
    const interval = setInterval(fetchFeedbackHistory, 60000)
    return () => clearInterval(interval)
  }, [userId, limit, showAutoFeedback])

  const getStarRating = (score: number): number => {
    // Convert 0-100 score to 0-5 stars
    return Math.round((score / 100) * 5 * 10) / 10
  }

  const getCategoryIcon = (category: string | null) => {
    switch (category) {
      case 'game_performance':
        return <TrendingUp className="w-3 h-3 text-green-500" />
      case 'trade_execution':
        return <TrendingUp className="w-3 h-3 text-blue-500" />
      case 'social_interaction':
        return <MessageSquare className="w-3 h-3 text-purple-500" />
      default:
        return <Star className="w-3 h-3 text-gray-500" />
    }
  }

  const getCategoryLabel = (category: string | null): string => {
    switch (category) {
      case 'game_performance':
        return 'Game'
      case 'trade_execution':
        return 'Trade'
      case 'social_interaction':
        return 'Social'
      default:
        return 'General'
    }
  }

  const truncateComment = (comment: string, maxLength: number = 100): string => {
    if (comment.length <= maxLength) return comment
    return comment.slice(0, maxLength) + '...'
  }

  return (
    <div className={`bg-sidebar rounded-lg p-4 ${className}`}>
      <div className="flex items-center justify-between mb-3">
        <div className="flex items-center gap-2">
          <MessageSquare className="w-5 h-5 text-[#1c9cf0]" />
          <h2 className="text-xl font-bold text-foreground">Feedback History</h2>
        </div>
        {!loading && feedbackItems.length > 0 && (
          <div className="flex items-center gap-1 text-sm text-muted-foreground">
            <Star className="w-4 h-4 text-yellow-500" fill="currentColor" />
            <span className="font-semibold">
              {getStarRating(averageScore).toFixed(1)}
            </span>
            <span>/5</span>
          </div>
        )}
      </div>

      {loading ? (
        <div className="text-sm text-muted-foreground">Loading feedback...</div>
      ) : feedbackItems.length === 0 ? (
        <div className="text-sm text-muted-foreground">
          No feedback received yet. Complete games to receive feedback!
        </div>
      ) : (
        <div className="space-y-3">
          {feedbackItems.map((feedback) => {
            const feedbackDate = new Date(feedback.createdAt)
            const timeAgo = formatDistanceToNow(feedbackDate, { addSuffix: true })
            const starRating = getStarRating(feedback.score)

            return (
              <div
                key={feedback.id}
                className="bg-muted/30 rounded-lg p-3 hover:bg-muted/50 transition-colors"
              >
                {/* Header */}
                <div className="flex items-center justify-between mb-2">
                  <div className="flex items-center gap-2">
                    {feedback.isAutoGenerated ? (
                      <div className="flex items-center gap-1 text-xs text-blue-500">
                        <AlertCircle className="w-3 h-3" />
                        <span>Auto-Generated</span>
                      </div>
                    ) : feedback.fromUserName ? (
                      <Link
                        href={getProfileUrl(
                          feedback.fromUserId || '',
                          feedback.fromUsername
                        )}
                        className="font-semibold text-sm text-foreground hover:underline"
                      >
                        {feedback.fromUserName}
                      </Link>
                    ) : (
                      <span className="text-sm text-muted-foreground">System</span>
                    )}
                    {feedback.category && (
                      <div className="flex items-center gap-1">
                        {getCategoryIcon(feedback.category)}
                        <span className="text-xs text-muted-foreground">
                          {getCategoryLabel(feedback.category)}
                        </span>
                      </div>
                    )}
                  </div>
                  <span className="text-xs text-muted-foreground">{timeAgo}</span>
                </div>

                {/* Star Rating */}
                <div className="flex items-center gap-1 mb-2">
                  {[1, 2, 3, 4, 5].map((star) => (
                    <Star
                      key={star}
                      className={`w-4 h-4 ${
                        star <= Math.floor(starRating)
                          ? 'text-yellow-500'
                          : star <= starRating
                          ? 'text-yellow-500/50'
                          : 'text-gray-600'
                      }`}
                      fill={star <= starRating ? 'currentColor' : 'none'}
                    />
                  ))}
                  <span className="text-sm text-muted-foreground ml-1">
                    {starRating.toFixed(1)}/5 ({feedback.score}/100)
                  </span>
                </div>

                {/* Comment */}
                {feedback.comment && (
                  <p className="text-sm text-foreground line-clamp-2 break-words">
                    {truncateComment(feedback.comment, 120)}
                  </p>
                )}
              </div>
            )
          })}
        </div>
      )}
    </div>
  )
}

/**
 * FeedbackSummaryCard Component
 *
 * Compact card showing feedback stats
 */
interface FeedbackSummaryCardProps {
  userId: string
  className?: string
}

export function FeedbackSummaryCard({
  userId,
  className = ''
}: FeedbackSummaryCardProps) {
  const [stats, setStats] = useState({
    averageScore: 0,
    totalFeedback: 0,
    recentTrend: 0,
  })
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    const fetchStats = async () => {
      const response = await fetch(
        `/api/feedback/stats/${encodeURIComponent(userId)}`
      )
      const data = await response.json()

      if (data.success) {
        setStats({
          averageScore: data.averageScore || 0,
          totalFeedback: data.totalCount || 0,
          recentTrend: data.recentTrend || 0,
        })
      }
      setLoading(false)
    }

    fetchStats()
  }, [userId])

  if (loading) return null

  const starRating = Math.round((stats.averageScore / 100) * 5 * 10) / 10

  return (
    <div className={`bg-muted/30 rounded-lg p-3 ${className}`}>
      <div className="flex items-center justify-between">
        <div>
          <div className="flex items-center gap-1 mb-1">
            <Star className="w-5 h-5 text-yellow-500" fill="currentColor" />
            <span className="text-2xl font-bold text-foreground">
              {starRating.toFixed(1)}
            </span>
            <span className="text-sm text-muted-foreground">/5</span>
          </div>
          <div className="text-xs text-muted-foreground">
            {stats.totalFeedback} review{stats.totalFeedback !== 1 ? 's' : ''}
          </div>
        </div>
        {stats.recentTrend !== 0 && (
          <div
            className={`flex items-center gap-1 text-xs font-medium ${
              stats.recentTrend > 0 ? 'text-green-500' : 'text-red-500'
            }`}
          >
            {stats.recentTrend > 0 ? (
              <TrendingUp className="w-4 h-4" />
            ) : (
              <TrendingDown className="w-4 h-4" />
            )}
            <span>{Math.abs(stats.recentTrend).toFixed(1)}%</span>
          </div>
        )}
      </div>
    </div>
  )
}
